### PR TITLE
Updates to Helsinki Agenda and Speakers

### PR DESCRIPTION
**Pull request by dmueller2001**
Cleaned up Agenda, Speakers and timings

@wgordon17 @jiri-fiala @tahonen

### CODE REVIEW

**Comment by TanjaRepo** [comment]
I would need and update for the tickets 
- update my email address to Eventbrite
from 'Opening soon' (button creates href mailto trepo@redhat.com) 
to
https://www.eventbrite.com/e/openshift-commons-gathering-in-finland-helsinkiespoo-tickets-47832236507

**Comment by wgordon17** [comment]
Hi @TanjaRepo, since this PR has already been merged, it would be appreciated if you were able to submit a new pull request.

Thank you!

**Comment by TanjaRepo** [comment]
Thx @wgordon17 for #protip - will do ;)

**Comment by tahonen** [comment]
I can do new PR later today

**Pull request merged**
