### PR TITLE
Added sponsors to Seattle

### PR DESCRIPTION
**Pull request by LuminousCoder**
Added StorageOS and Tremolo Security

### CODE REVIEW

**Comment by wgordon17** [comment]
@jiri-fiala Looks like the commit is missing the images.

**Comment by LuminousCoder** [comment]
What is the best way to specify the image? The sponsor logos seem to exist already, so I referenced them like below:
`logo: "commons-logos/tremolo.png"`

**Comment by wgordon17** [comment]
@LuminousCoder 

I'm sorry, I thought this was a completely different PR...that's what I get for looking at this too quickly. I've update the PR with an additional commit. If the company already exists in [the participants file](https://github.com/openshift-cs/commons.openshift.org/blob/master/data/participants.yml), you can simply specify the `name` value here and it'll pick up both the logo and link.

**Comment by wgordon17** [comment]
@LuminousCoder This is live now, https://commons.openshift.org/gatherings/Seattle_2018.html#gathering-sponsor

Thanks for your PR 😄

**Pull request merged**
